<?php

/********************************************************************************
 * This file was automatically generated by the version-loader-generator script
 * whenever the composer update command is run.
 *
 * WARNING: Do not modify this file directly. Your changes will be overwritten.
 *******************************************************************************/

use PublishPress\PimplePimple\VersionLoader;

class VersionLoaderCest
{
    public function testAllVersionsAreRegistered(IntegrationTester $I)
    {
        $loader = VersionLoader::getInstance();

        $registeredVersions = $loader->getVersions();

        $I->assertNotEmpty($registeredVersions);
        $I->assertEquals([
            '2.0.0.1' => 'PublishPress\PimplePimple\initialize2Dot0Dot0Dot1',
            '2.0.0.2' => 'PublishPress\PimplePimple\initialize2Dot0Dot0Dot2',
            '3.5.0.11' => 'PublishPress\PimplePimple\initialize3Dot5Dot0Dot11',
        ], $registeredVersions);
    }

    public function testLatestVersionIsTheCurrentVersion(IntegrationTester $I)
    {
        $loader = VersionLoader::getInstance();

        $latestVersion = $loader->latestVersion();

        $I->assertEquals('3.5.0.11', $latestVersion);
    }

    public function testLatestVersionCallbackIsTheLastOne(IntegrationTester $I)
    {
        $loader = VersionLoader::getInstance();

        $latestVersionCallback = $loader->latestVersionCallback();

        $I->assertEquals('PublishPress\PimplePimple\initialize3Dot5Dot0Dot11', $latestVersionCallback);
    }

    public function testInitializeLatestVersion(IntegrationTester $I)
    {
        $loader = VersionLoader::getInstance();

        $loader->initializeLatestVersion();

        $I->assertTrue(class_exists('PublishPress\Pimple\Container'));

        $didAction = (bool)did_action('publishpress_pimple_pimple_3Dot5Dot0Dot11_initialized');
        $I->assertTrue($didAction);
    }
}
